random_events:
  land_price:
    min: 17
    max: 26

  wheat_yield:
    min: 1
    max: 6

  rats_activity:
    min_percent: 0
    max_percent: 7

  migration:
    min: 0
    max: 50

  plague:
    chance: 0.15 #
